### ISSUE TITLE
Install kernel headers as part of image building for flintlock-kernel `5.10.77`

### ISSUE THREAD

**Issue by nikimanoledaki** [weaveworks-liquidmetal/image-builder#39]
I tried to install kernel headers by following [this](https://www.tecmint.com/install-kernel-headers-in-ubuntu-and-debian/) tutorial.

Since this kernel is custom, there were no results when searching for headers for 5.10.77 :
```
apt search linux-headers-$(uname -r)
Sorting... Done
Full Text Search... Done 
```

This leads to an error when trying to install headers for 5.10.77:
```
apt install linux-headers-$(uname -r)
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package linux-headers-5.10.77
E: Couldn't find any package by glob 'linux-headers-5.10.77'
```

~Is this something that the images could support or is it out of scope? Any help would be appreciated, thank you :)~

**Comment by nikimanoledaki** [comment]
This should be possible by adding a line after [this one](https://github.com/weaveworks-liquidmetal/image-builder/blob/main/flintlock/kernel/Dockerfile#L22) to make the kernel headers :)

**Comment by Callisto13** [comment]
We are making changes so that the kernel binary and modules are supplied as additional volumes and mounted in. They will no longer be part of the OS image chain.

So in future if you want extra things you can build an image containing just those things and have it mounted in at the location you need.

Closing
